---
  server:
    address:
    port: 8080
  spring:
    application:
      name: sights-on-map-api
    datasource:
      url: jdbc:postgresql://localhost:5432/sights_on_map_api
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: validate
      properties:
        open-in-view: false
        show_sql: true
        hibernate:
          dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    flyway:
      enabled: true
      baseline-on-migrate: true
      create-schemas: true
      locations: classpath:db/migration
      #driver-class-name: org.postgresql.Driver