-- Включаем PostGIS
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE feedback
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sight_id   BIGINT                                  NOT NULL,
    username   VARCHAR(255)                            NOT NULL,
    text       TEXT,
    estimation INTEGER                                 NOT NULL,
    CONSTRAINT pk_feedback PRIMARY KEY (id)
);

CREATE TABLE sight
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    city     VARCHAR(255)                            NOT NULL,
    position GEOGRAPHY(Point, 4326)                  NOT NULL,
    category VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sight PRIMARY KEY (id)
);

ALTER TABLE sight
    ADD CONSTRAINT uc_sight_name UNIQUE (name);

ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_SIGHT FOREIGN KEY (sight_id) REFERENCES sight (id);

DROP TABLE spatial_ref_sys CASCADE;